apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    pv: mysql-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.100.202
    path: "/data1/database"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  selector:
    matchLabels:
      pv: mysql-pv-volume